[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm install",
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "cd backend && npx prisma generate"
]

[start]
cmd = "node backend/init-db.js && node backend/server.js"
